class_name EncounterResolutionModes

# Most encounters will be wave based. Below a list of possible Resolution modes and some characteristics. Objective type that do not feature an encounter have been left out of this list.
const COMBAT := "combat" # Combat trails are not wave based. The echoes must simply beat a set of enemies to proceed. Winning condition is defeat of all enemies.
const SURVIVAL := "survival" # This is similar to COMBAT only in this resolution the echoes must survive a number of waves. Winning condition is survival of at least 1 echo
const PURIFY_SHRINE := "purify_shrine" # Echoes must purify a shrine that is placed in a random location on the map, while dealing with waves of enemies that are trying to destroy this shrine. The echoes must first find the hidden shrine and then protect it from the enemy waves. Winning condition is shrine protect (health is not 0) and at least one echo alive after all waves completed. Echos with specific can of stats can purify the shrine (restore health) slighty as an action instead of attacking or defending. Only if the shrin is below 50% health. 
const PROTECT_TOTEM := "protect_totem" # Similar to purify shrine only a totem can be carried (60% chance it can be). The carried totem debufs the totem holder. Yet again enemy waves are trying to destroy the totem. Enemies can steal the totem and deal double damage. This is a game of placement and defence. Specific kind of state/clases can reduce the debuff. Winning conditions are totem has health and at least one echo is alive. There is a chance after the stage that the totem can be rewarded to the player as an item.
const GUIDE_SPIRIT := "guide_spirit" # Echoes must find the spirit and either protect them in place or guide them to a certain location on the map. In case of escort there is a 50% chance that the spirit can join in battle with a 75% damage debuff. Winning conditions spirit alive and at least one echo alive or succesfull escort to location and one echo alive. There is a chance for the player to get the spirit as a free summon if spirit has been protected succesfully.
# more modes could be added later on.
